/**
 * Represents an error that is caused by invalid tool call request.
 *
 * @public
 * @experimental [EXP-GRANULAR-ACT] More granular .act status reporting is experimental and may
 * change in the future
 */
export class ToolCallRequestError extends Error {
  public constructor(
    message: string,
    /**
     * The raw output that was generated by the model before the tool call. The exact nature of this
     * fields depends on the error. It sometimes include the entire tool calls section, or sometimes
     * just the single tool call that failed.
     *
     * This field is not always available, and may be `undefined`.
     *
     * @experimental [EXP-GRANULAR-ACT] More granular .act status reporting is experimental and may
     * change in the future
     * @experimental [EXP-NON-ACT-TOOL-CALLBACKS] Tool call callbacks in .respond/.complete is in an
     * experimental feature. This may change in the future without warning.
     */
    public readonly rawContent: string | undefined,
  ) {
    super(message);
  }
}
